[tool.ruff]
line-length = 88
indent-width = 4

[tool.ruff.format]
quote-style = "single"
indent-style = "space"

docstring-code-format = true

[project]
name = "sewsource"
version = "0.0.1"
dependencies = ["rich", "click", "GitPython"]
